experiments:
- experiment_name: more_digit_lr_0001_cuda_aug_drop
  architecture: [784, 512, 256, 10]
  activation: relu  # "relu", "sigmoid", "tanh"
  output_activation: softmax  # "softmax", "sigmoid"
  loss: cross_entropy  # "cross_entropy", "mse"
  optimizer: adam  # "adam", "sgd"
  learning_rate: 0.001
  batch_size: 1024
  epochs: 100
  train_val_split: 0.8
  seed: 42
  dropout: 0.2  # Probabilidad de Dropout (0.0 para desactivar)
  backend: cuda  # "cpu", "cuda", "tensor"
  augmentation: # WARNING: ONLY GPU SUPPORTED
    enabled: true 
    alpha: 36.0 # Escala de la deformación elástica
    sigma: 5.0 # Suavizado de la deformación elástica (Gaussian blur)
    rotation_range: 15.0 # Rango de rotación en grados (ej: -15 a 15)
    scale_range: 0.15 # Variación de escala (ej: 0.85 a 1.15)